services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Netlogix\Nxsolrajax\:
    resource: '../Classes/*'
    exclude: '../Classes/Event/*'

  Netlogix\Nxsolrajax\Compatibility\LinkHelperReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-linkHelper'
        method: 'generateFacetResetUrl'
        event: Netlogix\Nxsolrajax\Event\Url\GenerateFacetResetUrlEvent
      - name: event.listener
        identifier: 'legacy-linkHelper'
        method: 'generateFacetItemUrl'
        event: Netlogix\Nxsolrajax\Event\Url\GenerateFacetItemUrlEvent

  Netlogix\Nxsolrajax\Compatibility\ModifySuggestionsHookReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-modifySuggestions'
        event: Netlogix\Nxsolrajax\Event\Search\AfterGetSuggestionsEvent